import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-dim": "#c9dde9",
        "on-surface": "#0b1e26",
        "on-background": "#0b1e26",
        "on-secondary-fixed": "#0f1d25",
        "surface-container-low": "#e7f6ff",
        "inverse-primary": "#68dbae",
        "surface-variant": "#d2e5f1",
        "error-container": "#ffdad6",
        "outline-variant": "#bccac1",
        "on-secondary-fixed-variant": "#3b4951",
        "on-tertiary-fixed": "#002117",
        "secondary-container": "#d5e5ef",
        "primary-fixed-dim": "#68dbae",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#e1f4ff",
        "on-primary-container": "#f5fff7",
        "tertiary-container": "#008565",
        "secondary-fixed": "#d5e5ef",
        "primary-container": "#008560",
        "on-tertiary-container": "#f5fff8",
        "inverse-surface": "#21333c",
        "surface-bright": "#f4faff",
        "secondary": "#526069",
        "surface-container": "#ddf1fd",
        "on-surface-variant": "#3d4943",
        "surface-container-highest": "#d2e5f1",
        "tertiary": "#00694f",
        "on-tertiary-fixed-variant": "#00513d",
        "background": "#f4faff",
        "tertiary-fixed": "#8af7cf",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#00513a",
        "on-secondary-container": "#586670",
        "surface-container-high": "#d7ebf7",
        "secondary-fixed-dim": "#bac9d3",
        "surface-tint": "#006c4e",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#6edab4",
        "primary": "#00694c",
        "primary-fixed": "#86f8c9",
        "surface": "#f4faff",
        "outline": "#6d7a73",
        "on-primary-fixed": "#002115",
        "on-error-container": "#93000a",
        "surface-dark": "#1A2830",
        "accent": "#5DCAA5",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
} satisfies Config
